#
# Module manifest for module 'PSDev'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2022-12-21
#

@{
    RootModule           = 'PSDev.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '92f82248-3ce2-432c-92c5-6d1803aac085'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Various tools'
    RequiredModules      = @('indented.net.ip')
    FunctionsToExport    = '*'
    #CmdletsToExport      = '*'
    #VariablesToExport    = '*'
    #AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri   = 'https://github.com/hanpq/PSDev/blob/main/LICENSE'
            # Bug in PowershellGet 3.0.18-beta18 causes packaging of the nuget package to fail when requireLicenseAcceptance is defined.
            #RequireLicenseAcceptance = $false
            Prerelease   = ''
            Tags         = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri   = 'https://getps.dev/modules/PSDev/getstarted'
            ReleaseNotes = ''
        }
    }
}
