#
# Module manifest for module 'PSUtils'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2022-12-21
#

@{
    RootModule           = 'PSUtils.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '92f82248-3ce2-432c-92c5-6d1803aac085'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Various tools'
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            LicenseUri               = 'https://github.com/hanpq/PSUtils/blob/main/LICENSE'
            ProjectUri               = 'https://getps.dev/modules/PSUtils/getstarted'
            IconUri                  = ''
            ReleaseNotes             = ''
            RequireLicenseAcceptance = $false
        }
    }
}


